### ISSUE TITLE
Happened multiple times,black picture

### ISSUE THREAD

**Issue by yangnt** [gelasdev/ComfyUI-FLUX-BFL-API#1]
Use the api to generate the following

![thumbnail_image](https://github.com/user-attachments/assets/605ac282-4356-4bc5-b9a0-795502f45142)

**Comment by gelasdev** [comment]
Can you provide terminal log. This may be due to insufficient time.sleep(5) between post and get requests. You can try increase sleep duration and add print task id in case not loosing task id so you can get from BFL API directly. I planning to add recursive get request here.
```
if task_id:
    print(f"TaskId: {task_id}")
    time.sleep(10)
    return self.get_result(task_id)
```

**Comment by gelasdev** [comment]
I updated get request to recursive.

**Comment by yangnt** [comment]
> 我將 get 請求更新為 recursive。

NICE!
