### ISSUE TITLE
Output black picture & nsfw

### ISSUE THREAD

**Issue by walterFeng** [gelasdev/ComfyUI-FLUX-BFL-API#11]
Most of the time, nodes work perfectly. But I also often come across a black image output.
I have checked the BFL documentation, I can't find the description about it, I have the following questions?
1. Is there an error in the way the API is called in node (which I think is less likely)?
2. Is it a bug inside BFL?
3. Does BFL think the image is banned and return us a black image (I seem to have seen this process in other nodes, replacing the banned image with a black image)?
4. For case 3, can we determine whether the image is banned? If so, how can people using this node determine whether the image is banned? Are there any plans to add a boolean variable output (e.g. 'nsfw') in a later version?

The workflow example:
[flux-error.json](https://github.com/user-attachments/files/18079368/flux-error.json)

**Comment by gelasdev** [comment]
The BFL API does not directly return a black image; this likely indicates an error occurred during the process of sending the image to the API or receiving the image from the API. If an error occurs, the node will output a black image as a fallback. If you can provide detailed logs of the error from the terminal, I can examine them further to identify the issue.

Additionally, please note that the BFL API does not support NSFW content. If you input trigger keywords, you will receive a “Content Moderated” error.

<img width="560" alt="Screenshot 2024-12-10 at 15 34 54" src="https://github.com/user-attachments/assets/967082a5-f8a1-402f-aa42-3d9a662a1ff5">

**Comment by gelasdev** [comment]
<img width="848" alt="Screenshot 2024-12-10 at 16 11 47" src="https://github.com/user-attachments/assets/037c3355-f5c8-4026-adcb-af2a79ea0709">
you lose 1px but I dont know why

**Comment by walterFeng** [comment]
> <img alt="截图 2024-12-10 16 11 47" width="848" src="https://private-user-images.githubusercontent.com/46890564/394286472-037c3355-f5c8-4026-adcb-af2a79ea0709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTYzMjcsIm5iZiI6MTczMzkxNjAyNywicGF0aCI6Ii80Njg5MDU2NC8zOTQyODY0NzItMDM3YzMzNTUtZjVjOC00MDI2LWFkY2ItYWYyYTc5ZWEwNzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDExMjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhN2RkMmI2ZjdlY2FjYWViZDgwZGYwNTNlMTg2YmRkYzY3YzkwNzBkZTQyYTAxYzVjZDZlMWZlZjE4MDc2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oJmrEx809BZsdJKL_6IzOvtsR1CgwdCPHiPi2HgVKDI"> 你失去或增加了 1px 但我不知道为什么

thanks for your help.
I thought it was because of nsfw that I got a black image. But actually my problem is that the picture and mask sizes don't match.
However, I still think that when nsfw content appears, the IMAGE output by node may be a picture with a black background. I will verify the following when I encounter nsfw content later
