### ISSUE TITLE
Please: make Support of Ultra and RAW models

### ISSUE THREAD

**Issue by ShmuelRonen** [gelasdev/ComfyUI-FLUX-BFL-API#4]
FLUX1.1 [pro] Breaks New Ground with Ultra and Raw Mode Capabilities
November 6, 2024 - BlackForestLabs
In a significant advancement for AI image generation, BlackForestLabs has unveiled two groundbreaking features for their FLUX1.1 [pro] platform: Ultra mode and Raw mode. These innovations represent a substantial leap forward in both image resolution capabilities and natural aesthetics, while maintaining the platform's renowned processing efficiency.
Ultra Mode: Redefining High-Resolution Generation
The newly introduced Ultra mode pushes the boundaries of image resolution, delivering outputs at an impressive 4 megapixels—four times the standard resolution of FLUX1.1 [pro]. What sets this achievement apart is the platform's ability to maintain rapid generation speeds despite the increased complexity. With image creation taking just 10 seconds per sample, FLUX1.1 [pro] Ultra mode operates 2.5 times faster than comparable high-resolution solutions in the market.

**Comment by gelasdev** [comment]
I added Flux ultra model with Raw feature. You can update it via Custom Nodes Manager or update manually.
