### ISSUE TITLE
Resolutions for Ultra and Pro

### ISSUE THREAD

**Issue by BtFormado** [gelasdev/ComfyUI-FLUX-BFL-API#5]
Hi There,

First big thanks for this API for Comfy UI, really appreciate it. I would like to ask some questions : 

As black forest announced the models support 2-megapixels image for Pro 1.1 and for Ultra 2megapixels the problem is the script for Pro 1.1 lock at 1440 if you set different ration for example 16/9 is equal 1886*1061 but also at Black forest, they mentioned this we could set HD or basically if the number is divided by 64, this resolve 2 megapixels 1920*1088 I'm running local and works on the dev Flux so for Ultra 4 megapixel would be 2667*1500 and divide by 64 = 2688*1536 on the ratio 16/9

different ratios different sizes  as you can see we can't set the size pixel higher cause the script block and limited pixel at 1440 this section

class FluxPro11(BaseFlux):
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "prompt": ("STRING", {"default": "", "multiline": True}),
                "width": ("INT", {"default": 1440, "min": 256, "max": 1440}),
                "height": ("INT", {"default": 1440, "min": 256, "max": 1440}),

is that any reason for that? why no options of resolution for Ultra and why not use the full 2megapixels for dev/pro etc and 4megapixel for ultra?

it would be simple to have an option to choose the ratio and then the megapixels 1mp or 2mp and for ultra 1mp, 2mp or 4mp

Kind Regards

**Comment by gelasdev** [comment]
Hi

https://api.bfl.ml/scalar

I add all limitation based on their API. I think i I should update aspect ratio for ultra. But I don't see any 2mp exc for option in documentation. Maybe I miss something? 

<img width="1424" alt="Screenshot 2024-11-08 at 23 22 40" src="https://github.com/user-attachments/assets/d3354a78-559d-4ccb-8f3f-83935594c4ba">
<img width="1386" alt="Screenshot 2024-11-08 at 23 23 07" src="https://github.com/user-attachments/assets/eae34ea6-7595-4730-a0af-843aeb4dacb0">

**Comment by gelasdev** [comment]
I updated the 'aspect_ratio' to a STRING for ultra, so you can now provide any aspect ratio with the new version. However, it will throw an error if you provide an invalid aspect ratio that is not between 21:9 and 9:21.

**Comment by BtFormado** [comment]
I was testing more the Ultra actually is fine the default is 16/9 on 4mp the images received is actually big I didn't realise before sorry about that, I need test different ratios but images I always do 16/9 so all good for now but is great Idea where we can choose I think what you did is not bad 16:9, 1:1, 4:3  but I think the usually ratios supported is 16:9, 1:1, 4:3, 3:2, 21:9 and the the reverted ratio 9:16, 1:1, 3:4, 2:3, 9:21 for portrait. is the only one supported with flux. thanks again for the update

**Comment by BtFormado** [comment]
By the way, I tested and edit and tested to see works perfectly with no errors I edited this line :

"aspect_ratio": (["16:9", "4:3", "1:1", "3:2", "21:9","9:16", "3:4", "2:3", "9:21"], {"default": "16:9"}),

Thanks to point out aswell for me I think if you add like that  but not "string" will avoid errors

**Comment by gelasdev** [comment]
Thank you! I updated the aspect_ratio parameter based on the code you provided.
