### ISSUE TITLE
img_converted.show()  issue

### ISSUE THREAD

**Issue by alenknight** [gelasdev/ComfyUI-FLUX-BFL-API#7]
great node set btw.  very clean and easy to use.  good job with this.  appreciate your work. :)

in the api node - line 70 - you have the node forcing to open and save the image to temp folder (by default it goes to temp)... 
in particular - img_converted.show() - this is causing the OS to open the image on the desktop every time someone runs your node.  
in my case, i'm running remotely.... so when i get back to my desktop , i have thousands of images eating up memory on my desktop.

commenting it out helped temporarily.... stopped the previews and temp file creation.... 

hopefully you can address this in a later build to disable this by default.

**Comment by gelasdev** [comment]
Thank you for pointing that out! I’ve fixed the issue.

Appreciate your feedback!

**Comment by alenknight** [comment]
awesome.  thanks!  ive been using it extensively with it just commented out, so i'm sure it works just fine. will update and report but this can be closed for now... i'm confident that fix alone will work.
