### ISSUE TITLE
What's with the black picture popping out?

### ISSUE THREAD

**Issue by WYY-gogogo** [gelasdev/ComfyUI-FLUX-BFL-API#9]
充值成功了，账户里有余额，跑出来是黑图。怎么办

**Comment by gelasdev** [comment]
Hello, which node are you having problems with. Is it possible to send terminal log. It works when I try it on my side. Are you using the latest version of node and ComfyUI?

**Comment by WYY-gogogo** [comment]
Has been resolved. The reason for the black picture is that the prompt is too long。。。。



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 6, 2024 15:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gelasdev/ComfyUI-FLUX-BFL-API] What's with the black picturepopping out? (Issue #9)




 
Hello, which node are you having problems with. Is it possible to send terminal log. It works when I try it on my side. Are you using the latest version of node and ComfyUI?
